# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5206f85175e6bc4df7ce15dab9bbe338cccf8a828d41ee81f42c4ff87bfd7804c59be1fe63cc4d5778e36d076f56dc06de413be8cc215420dc0e34f486a3d310

test:
  secret_key_base: b978f5be8436f87f420154c4c468ca5adc8cf1bf3c20bb39e283c8a9af0ec9a8eda957a0e32b057e5814687c433092fe1300837f66d244b06615375a8afe8c7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
